# Generated by Django 3.2 on 2025-02-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='user/avatar/', verbose_name='Аватар'),
        ),
    ]
